# Generated by Django 3.2.5 on 2021-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('customer', models.CharField(max_length=30, verbose_name='Покупатель')),
                ('item', models.CharField(max_length=30, verbose_name='Название камня')),
                ('total', models.IntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='количество купленных камней')),
                ('date', models.DateTimeField(max_length=30, verbose_name='Дата совершения сделки')),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
